title: ESCU - Linux Possible Append Command To Profile Config File - Rule
description: This analytic looks for suspicious command-lines that can be possibly
  used to modify user profile files to automatically execute scripts/executables by
  shell upon reboot of the machine. This technique is commonly abused by adversaries,
  malware and red teamers as persistence mechanism to the targeted or compromised
  host. This Anomaly detection is a good indicator that someone wants to run code
  after reboot which can be done also by the administrator or network operator for
  automation purposes.
status: Missing Data Source
author: DS
logsource:
  product: Splunk
  service: splunkd
  category: Linux
detection:
  condition:
    sigma: "\n  -  tstats `security_content_summariesonly` count min(_time) as firstTime\
      \ max(_time) as lastTime from datamodel=Endpoint.Processes where Processes.process\
      \ = \"*echo*\" AND Processes.process IN(\"*~/.bashrc\", \"*~/.bash_profile\"\
      , \"*/etc/profile\", \"~/.bash_login\", \"*~/.profile\", \"~/.bash_logout\"\
      ) by Processes.dest Processes.user Processes.parent_process_name Processes.process_name\
      \ Processes.process Processes.process_id Processes.parent_process_id Processes.process_guid\
      \ \n  -  `drop_dm_object_name(Processes)` \n  -  `security_content_ctime(firstTime)`\
      \ \n  -  `security_content_ctime(lastTime)` \n  -  `linux_possible_append_command_to_profile_config_file_filter`"
  level: critical
tags:
- "T1546.004\nT1546"
- 'Event Triggered Execution: Unix Shell Configuration Modification'
- 'Event Triggered Execution: Unix Shell Configuration Modification'
references: Increase Linux Logs to include Command Line data
notes: .nan
