title: ESCU - System Info Gathering Using Dxdiag Application - Rule
description: This analytic is to detect a suspicious dxdiag.exe process command-line
  execution. Dxdiag is used to collect the system info of the target host. This technique
  has been used by Remcos RATS, various actors, and other malware to collect information
  as part of the recon or collection phase of an attack. This behavior should rarely
  be seen in a corporate network, but this command line can be used by a network administrator
  to audit host machine specifications. Thus in some rare cases, this detection will
  contain false positives in its results. To triage further, analyze what commands
  were passed after it pipes out the result to a file for further processing.
status: Missing Data Source
author: DS
logsource:
  product: Splunk
  service: splunkd
  category: Windows
detection:
  condition:
    sigma: "\n  -  tstats `security_content_summariesonly` count min(_time) as firstTime\
      \ max(_time) as lastTime from datamodel=Endpoint.Processes where `process_dxdiag`\
      \ AND Processes.process = \"* /t *\" by Processes.dest Processes.user Processes.parent_process_name\
      \ Processes.parent_process Processes.process_name Processes.process Processes.process_id\
      \ Processes.parent_process_id \n  -  `drop_dm_object_name(Processes)` \n  -\
      \  `security_content_ctime(firstTime)` \n  -  `security_content_ctime(lastTime)`\
      \ \n  -  `system_info_gathering_using_dxdiag_application_filter`"
  level: critical
tags:
- T1592
- Gather Victim Host Information
- Reconnaissance
references: Increase Windows logging to include command line data
notes: .nan
