title: ESCU - Msmpeng Application DLL Side Loading - Rule
description: This search is to detect a suspicious creation of msmpeng.exe or mpsvc.dll
  in non default windows defender folder. This technique was seen couple days ago
  with revil ransomware in Kaseya Supply chain. The approach is to drop an old version
  of msmpeng.exe to load the actual payload name as mspvc.dll which will load the
  revil ransomware to the compromise machine
status: Missing Data Source
author: DS
logsource:
  product: Splunk
  service: splunkd
  category: Windows
detection:
  condition:
    sigma: "\n  - tstats `security_content_summariesonly` values(Filesystem.file_path)\
      \ as file_path count min(_time) as firstTime max(_time) as lastTime from datamodel=Endpoint.Filesystem\
      \ where (Filesystem.file_name = \"msmpeng.exe\" OR Filesystem.file_name = \"\
      mpsvc.dll\")  AND Filesystem.file_path != \"*\\\\Program Files\\\\windows defender\\\
      \\*\" by Filesystem.file_create_time Filesystem.process_id  Filesystem.file_name\
      \ Filesystem.user \n  -  `drop_dm_object_name(Processes)` \n  -  `security_content_ctime(firstTime)`\
      \ \n  -  `security_content_ctime(lastTime)` \n  -  `msmpeng_application_dll_side_loading_filter`"
  level: critical
tags:
- "T1574.002\nT1574"
- 'Hijack Execution Flow: DLL Side-Loading'
- 'Hijack Execution Flow: DLL Side-Loading'
references: Increase Windows logging to include file modification data
notes: .nan
