title: ESCU - Linux Possible Append Command To At Allow Config File - Rule
description: This analytic looks for suspicious commandline that may use to append
  user entry to /etc/at.allow or /etc/at.deny. These 2 files are commonly abused by
  malware, adversaries or red teamers to persist on the targeted or compromised host.
  These config file can restrict user that can only execute at application (another
  schedule task application in linux). attacker can create a user or add the compromised
  username to that config file to execute at to schedule it malicious code. This anomaly
  detection can be a good indicator to investigate further the entry in created config
  file and who created it to verify if it is a false positive.
status: Missing Data Source
author: DS
logsource:
  product: Splunk
  service: splunkd
  category: Linux
detection:
  condition:
    sigma: "\n  -  tstats `security_content_summariesonly` count from datamodel=Endpoint.Processes\
      \ where Processes.process = \"*echo*\" AND Processes.process IN(\"*/etc/at.allow\"\
      , \"*/etc/at.deny\") by Processes.dest Processes.user Processes.parent_process_name\
      \ Processes.process_name Processes.process Processes.process_id Processes.parent_process_id\
      \ Processes.process_guid \n  -  `drop_dm_object_name(Processes)` \n  -  `security_content_ctime(firstTime)`\
      \ \n  -  `security_content_ctime(lastTime)` \n  -  `linux_possible_append_command_to_at_allow_config_file_filter`"
  level: critical
tags:
- "T1053.002\nT1053"
- 'Scheduled Task/Job: At'
- 'Scheduled Task/Job: At'
references: Increase Linux Logs to include Command Line data
notes: .nan
