title: ESCU - Linux Possible Access Or Modification Of sshd Config File - Rule
description: This analytic is to look for suspicious process command-line that might
  be accessing or modifying sshd_config. This file is the ssh configuration file that
  might be modify by threat actors or adversaries to redirect port connection, allow
  user using authorized key generated during attack. This anomaly detection might
  catch noise from administrator auditing or modifying ssh configuration file. In
  this scenario filter is needed
status: Missing Data Source
author: DS
logsource:
  product: Splunk
  service: splunkd
  category: Linux
detection:
  condition:
    sigma: "\n  -  tstats `security_content_summariesonly` count min(_time) as firstTime\
      \ max(_time) as lastTime from datamodel=Endpoint.Processes where Processes.process_name\
      \ IN(\"cat\", \"nano*\",\"vim*\", \"vi*\")  AND Processes.process IN(\"*/etc/ssh/sshd_config\"\
      ) by Processes.dest Processes.user Processes.parent_process_name Processes.process_name\
      \ Processes.process Processes.process_id Processes.parent_process_id \n  - \
      \ `drop_dm_object_name(Processes)` \n  -  `security_content_ctime(firstTime)`\
      \ \n  -  `security_content_ctime(lastTime)` \n  -  `linux_possible_access_or_modification_of_sshd_config_file_filter`"
  level: critical
tags:
- "T1098.004\nT1098"
- 'Account Manipulation: SSH Authorized Keys'
- 'Account Manipulation: SSH Authorized Keys'
references: Increase Linux Logs to include Command Line data
notes: .nan
