title: ESCU - Detect Rundll32 Application Control Bypass - syssetup - Rule
description: The following analytic identifies rundll32.exe loading syssetup.dll by
  calling the LaunchINFSection function on the command line. This particular technique
  will load script code from a file. Upon a successful execution, the following module
  loads may occur - clr.dll, jscript.dll and scrobj.dll. During investigation, identify
  script content origination. Generally, a child process will spawn from rundll32.exe,
  but that may be bypassed based on script code contents. Rundll32.exe is natively
  found in C:\Windows\system32 and C:\Windows\syswow64. During investigation, review
  any network connections and obtain the script content executed. It's possible other
  files are on disk.
status: Missing Data Source
author: DS
logsource:
  product: Splunk
  service: splunkd
  category: Windows
detection:
  condition:
    sigma: "\n  -  tstats `security_content_summariesonly` count min(_time) as firstTime\
      \ max(_time) as lastTime from datamodel=Endpoint.Processes where `process_rundll32`\
      \ Processes.process=*syssetup* by Processes.dest Processes.user Processes.parent_process_name\
      \ Processes.original_file_name Processes.process_name Processes.process Processes.process_id\
      \ Processes.parent_process_id \n  -  `drop_dm_object_name(Processes)` \n  -\
      \  `security_content_ctime(firstTime)` \n  -  `security_content_ctime(lastTime)`\
      \ \n  -  `detect_rundll32_application_control_bypass___syssetup_filter`"
  level: critical
tags:
- "T1218\nT1218.011"
- System Binary Proxy Execution
- System Binary Proxy Execution
references: Increase Windows logging to include command line data
notes: .nan
