title: ESCU - MacOS - Re-opened Applications - Rule
description: This search looks for processes referencing the plist files that determine
  which applications are re-opened when a user reboots their machine.
status: Missing Data Source
author: DS
logsource:
  product: Splunk
  service: splunkd
  category: .nan
detection:
  condition:
    sigma: "\n  -  tstats `security_content_summariesonly` count values(Processes.process)\
      \ as process values(Processes.parent_process) as parent_process min(_time) as\
      \ firstTime max(_time) as lastTime from datamodel=Endpoint.Processes where Processes.process=\"\
      *com.apple.loginwindow*\" by Processes.user Processes.process_name Processes.parent_process_name\
      \ Processes.dest \n  -  `drop_dm_object_name(Processes)` \n  -  `security_content_ctime(firstTime)`\
      \ \n  -  `security_content_ctime(lastTime)` \n  -  `macos___re_opened_applications_filter`"
  level: critical
tags:
- T1059.004
- 'Command and Scripting Interpreter: Unix Shell'
- Execution
references: .nan
notes: "MacOS logs required\nTHIS IS A EXPERIMENTAL DETECTION"
