title: ESCU - Sdelete Application Execution - Rule
description: This analytic is to detect the execution of sdelete.exe application sysinternal
  tools. This tool is one of the most use tool of malware and adversaries to remove
  or clear their tracks and artifact in the targetted host. This tool is designed
  to delete securely a file in file system that remove the forensic evidence on the
  machine. A good TTP query to check why user execute this application which is not
  a common practice.
status: Missing Data Source
author: DS
logsource:
  product: Splunk
  service: splunkd
  category: Windows
detection:
  condition:
    sigma: "\n  -  tstats `security_content_summariesonly` values(Processes.process)\
      \ as process values(Processes.parent_process) as parent_process values(Processes.process_id)\
      \ as process_id count min(_time) as firstTime max(_time) as lastTime from datamodel=Endpoint.Processes\
      \ where `process_sdelete` by  Processes.process_name Processes.original_file_name\
      \ Processes.dest Processes.user Processes.parent_process_name Processes.parent_process\
      \ \n  -  `drop_dm_object_name(Processes)` \n  -  `security_content_ctime(firstTime)`\
      \ \n  -  `security_content_ctime(lastTime)` \n  -  `sdelete_application_execution_filter`"
  level: critical
tags:
- T1070.004
- 'Indicator Removal: File Deletion'
- Defense Evasion
references: Increase Windows logging to include command line data
notes: .nan
