title: ESCU - Change To Safe Mode With Network Config - Rule
description: This search is to detect a suspicious bcdedit commandline to configure
  the host to boot in safe mode with network config. This technique was seen in blackMatter
  ransomware where it force the compromised host to boot in safe mode to continue
  its encryption and bring back to normal boot using bcdedit deletevalue command.
  This TTP can be a good alert for host that booted from safe mode forcefully since
  it need to modify the boot configuration to bring it back to normal.
status: Missing Data Source
author: DS
logsource:
  product: Splunk
  service: splunkd
  category: Windows
detection:
  condition:
    sigma: "\n  -  tstats `security_content_summariesonly` count min(_time) as firstTime\
      \ max(_time) as lastTime from datamodel=Endpoint.Processes where Processes.process_name\
      \ = bcdedit.exe Processes.process=\"*/set*\" Processes.process=\"*{current}*\"\
      \  Processes.process=\"*safeboot*\" Processes.process=\"*network*\" by Processes.process_name\
      \ Processes.process Processes.parent_process_name Processes.dest Processes.user\
      \ \n  - `drop_dm_object_name(Processes)` \n  -  `security_content_ctime(firstTime)`\
      \ \n  -  `security_content_ctime(lastTime)` \n  -  `change_to_safe_mode_with_network_config_filter`"
  level: critical
tags:
- T1490
- Inhibit System Recovery
- Impact
references: Increase Windows logging to include command line data
notes: .nan
