title: ESCU - Detect Regsvr32 Application Control Bypass - Rule
description: "Adversaries may abuse Regsvr32.exe to proxy execution of malicious code.\
  \ Regsvr32.exe is a command-line program used to register and unregister object\
  \ linking and embedding controls, including dynamic link libraries (DLLs), on Windows\
  \ systems. Regsvr32.exe is also a Microsoft signed binary.This variation of the\
  \ technique is often referred to as a \"Squiblydoo\" attack. \nUpon investigating,\
  \ look for network connections to remote destinations (internal or external). Be\
  \ cautious to modify the query to look for \"scrobj.dll\", the \".dll\" is not required\
  \ to load scrobj. \"scrobj.dll\" will be loaded by \"regsvr32.exe\" upon execution."
status: Missing Data Source
author: DS
logsource:
  product: Splunk
  service: splunkd
  category: Windows
detection:
  condition:
    sigma: "\n  -  tstats `security_content_summariesonly` count min(_time) as firstTime\
      \ max(_time) as lastTime from datamodel=Endpoint.Processes where `process_regsvr32`\
      \ Processes.process=*scrobj* by Processes.dest Processes.user Processes.parent_process\
      \ Processes.process_name Processes.process Processes.original_file_name Processes.process_id\
      \ Processes.parent_process_id \n  -  `drop_dm_object_name(Processes)` \n  -\
      \  `security_content_ctime(firstTime)`\n  -  `security_content_ctime(lastTime)`\
      \ \n  -  `detect_regsvr32_application_control_bypass_filter`"
  level: critical
tags:
- "T1218\nT1218.010"
- System Binary Proxy Execution
- System Binary Proxy Execution
references: Increase Windows logging to include command line data
notes: .nan
