title: ESCU - Disabling CMD Application
description: this search is to identify modification in registry to disable cmd prompt
  application. This technique is commonly seen in RAT, Trojan or WORM to prevent triaging
  or deleting there samples through cmd application which is one of the tool of analyst
  to traverse on directory and files.
status: Missing Data Source
author: DS
logsource:
  product: Splunk
  service: splunkd
  category: .nan
detection:
  condition:
    sigma: "\n  -  tstats `security_content_summariesonly` count from datamodel=Endpoint.Registry\
      \ where Registry.registry_path= \"*\\\\SOFTWARE\\\\Policies\\\\Microsoft\\\\\
      Windows\\\\System\\\\DisableCMD\" Registry.registry_value_data = \"0x00000001\"\
      \ by _time span=1h Registry.dest Registry.user Registry.registry_path Registry.registry_value_name\
      \ Registry.registry_key_name Registry.process_guid Registry.registry_value_data\
      \ \n  -  `drop_dm_object_name(Registry)` \n  - rename process_guid as proc_guid\
      \ \n  - join proc_guid, _time [\n  -  tstats `security_content_summariesonly`\
      \ count FROM datamodel=Endpoint.Processes by _time span=1h Processes.process_id\
      \ Processes.process_name Processes.process Processes.dest Processes.parent_process_name\
      \ Processes.parent_process Processes.process_guid \n  -  `drop_dm_object_name(Processes)`\
      \ \n  - rename process_guid as proc_guid \n  -  fields _time dest user parent_process_name\
      \ parent_process process_name process_path process proc_guid registry_path registry_value_name\
      \ registry_value_data registry_key_name] \n  -  table _time dest user parent_process_name\
      \ parent_process process_name process_path process proc_guid registry_path registry_value_name\
      \ registry_value_data registry_key_name \n  -  `disabling_cmd_application_filter`"
  level: critical
tags:
- T1562.001
- 'Impair Defenses: Disable or Modify Tools'
- Defense Evasion
references: Increase Windows logging to include Registry events
notes: .nan
