title: ESCU - Detect Prohibited Applications Spawning cmd exe - Rule
description: This search looks for executions of cmd.exe spawned by a process that
  is often abused by attackers and that does not typically launch cmd.exe.
status: Active
author: DS
logsource:
  product: Splunk
  service: splunkd
  category: Windows
detection:
  condition:
    sigma: "\n  -  tstats `security_content_summariesonly` count values(Processes.process)\
      \ as process min(_time) as firstTime max(_time) as lastTime from datamodel=Endpoint.Processes\
      \ where `process_cmd` by Processes.parent_process_name Processes.process_name\
      \ Processes.original_file_name Processes.dest Processes.user\n  -  `drop_dm_object_name(Processes)`\
      \ \n  -  `security_content_ctime(firstTime)`\n  -  `security_content_ctime(lastTime)`\
      \ \n  - [`prohibited_apps_launching_cmd`] \n  -  `detect_prohibited_applications_spawning_cmd_exe_filter`"
  level: critical
tags:
- "T1059\nT1059.003"
- Command and Scripting Interpreter
- Command and Scripting Interpreter
references: .nan
notes: .nan
