title: ESCU - Office Application Drop Executable - Rule
description: This search is to detect a suspicious MS office application that drop
  or create executables or script in the host. This behavior is commonly seen in spear
  phishing office attachment where it drop malicious files or script to compromised
  the host. It might be some normal macro may drop script or tools as part of automation
  but still this behavior is reallly suspicious and not commonly seen in normal office
  application
status: Missing Data Source
author: DS
logsource:
  product: Splunk
  service: splunkd
  category: Windows
detection:
  condition:
    sigma: "\n  -  tstats `security_content_summariesonly` count FROM datamodel=Endpoint.Processes\
      \ where Processes.process_name IN (\"winword.exe\",\"excel.exe\",\"powerpnt.exe\"\
      ,\"mspub.exe\",\"visio.exe\",\"wordpad.exe\",\"wordview.exe\") by _time span=1h\
      \ Processes.process_id Processes.process_name Processes.process Processes.dest\
      \ Processes.process_guid \n  -  `drop_dm_object_name(Processes)` \n  - rename\
      \ process_guid as proc_guid \n  - join proc_guid, _time [\n  -  tstats `security_content_summariesonly`\
      \ count min(_time) as firstTime max(_time) as lastTime FROM datamodel=Endpoint.Filesystem\
      \ where Filesystem.file_name IN (\"*.exe\",\"*.dll\",\"*.pif\",\"*.scr\",\"\
      *.js\",\"*.vbs\",\"*.vbe\",\"*.ps1\") by _time span=1h Filesystem.dest Filesystem.file_create_time\
      \ Filesystem.file_name Filesystem.process_guid Filesystem.file_path \n  -  `drop_dm_object_name(Filesystem)`\
      \ \n  -  rename process_guid as proc_guid \n  -  fields _time dest file_create_time\
      \ file_name file_path process_name process_path process proc_guid] \n  -  dedup\
      \ file_create_time \n  -  table dest, process_name, process, file_create_time,\
      \ file_name, file_path, proc_guid \n  -  `office_application_drop_executable_filter`"
  level: critical
tags:
- "T1566\nT1566.001"
- Phishing
- Phishing
references: Increase Windows logging to include file modification data
notes: .nan
