title: ESCU - Linux At Allow Config File Creation - Rule
description: The following analytic identifies a suspicious file creation of /etc/at.allow
  or /etc/at.deny. These 2 files are commonly abused by malware, adversaries or red
  teamers to persist on the targeted or compromised host. These config files can restrict
  or allow user to execute "at" application (another schedule task application in
  linux). attacker can create a user or add the compromised username to that config
  file to execute "at" to schedule it malicious code. This anomaly detection can be
  a good indicator to investigate further the entry in created config file and who
  created it to verify if it is a false positive.
status: Missing Data Source
author: DS
logsource:
  product: Splunk
  service: splunkd
  category: Linux
detection:
  condition:
    sigma: "\n  -  tstats `security_content_summariesonly` count min(_time) as firstTime\
      \ max(_time) as lastTime FROM datamodel=Endpoint.Filesystem where Filesystem.file_path\
      \ IN (\"*/etc/at.allow\", \"*/etc/at.deny\") by Filesystem.dest Filesystem.file_create_time\
      \ Filesystem.file_name Filesystem.process_guid Filesystem.file_path \n  -  `drop_dm_object_name(Filesystem)`\
      \ \n  -  `security_content_ctime(lastTime)` \n  -  `security_content_ctime(firstTime)`\
      \ \n  -  `linux_at_allow_config_file_creation_filter`"
  level: critical
tags:
- "T1053.003\nT1053"
- 'Scheduled Task/Job: Cron'
- 'Scheduled Task/Job: Cron'
references: Increase Linux logging to include file creation, deletion and modification
notes: .nan
