title: ESCU - Windows Hidden Schedule Task Settings - Rule
description: The following query utilizes Windows Security EventCode 4698, A scheduled
  task was created, to identify suspicious tasks registered on Windows either via
  schtasks.exe OR TaskService with a hidden settings that are unique entry of malware
  like industroyer2 or attack that uses lolbin to download other file or payload to
  the infected machine.
status: Missing Data Source
author: DS
logsource:
  product: Splunk
  service: splunkd
  category: Windows
detection:
  condition:
    sigma: "`wineventlog_security` EventCode=4698 \n  -  xmlkv Message \n  -  Hidden\
      \ = true \n  -  stats count min(_time) as firstTime max(_time) as lastTime by\
      \  Task_Name, Command, Author, Hidden, dest \n  -  `security_content_ctime(firstTime)`\
      \ \n  -  `security_content_ctime(lastTime)` \n  -  `windows_hidden_schedule_task_settings_filter`"
  level: critical
tags:
- T1053
- Scheduled Task/Job
- Execution, Persistence, Privilege Escalation
references: Increase Windows logging to include command line data
notes: .nan
