title: ESCU - Office Application Spawn Regsvr32 process - Rule
description: this detection was designed to identifies suspicious spawned process
  of known MS office application due to macro or malicious code. this technique can
  be seen in so many malware like IcedID that used MS office as its weapon or attack
  vector to initially infect the machines.
status: Active
author: DS
logsource:
  product: Splunk
  service: splunkd
  category: Windows
detection:
  condition:
    sigma: "\n  -  tstats `security_content_summariesonly` count min(_time) as firstTime\
      \ max(_time) as lastTime from datamodel=Endpoint.Processes where (Processes.parent_process_name\
      \ = \"winword.exe\" OR Processes.parent_process_name = \"excel.exe\" OR Processes.parent_process_name\
      \ = \"powerpnt.exe\" OR Processes.parent_process_name = \"outlook.exe\") `process_regsvr32`\
      \ by Processes.parent_process_name Processes.parent_process Processes.process_name\
      \ Processes.original_file_name Processes.process Processes.process_id Processes.user\
      \ Processes.dest \n  -  `drop_dm_object_name(\"Processes\")` \n  -  `security_content_ctime(firstTime)`\
      \ \n  - `security_content_ctime(lastTime)` \n  -  `office_application_spawn_regsvr32_process_filter`"
  level: critical
tags:
- "T1566\nT1566.001"
- Phishing
- Phishing
references: .nan
notes: .nan
